### ISSUE TITLE
ImportError: cannot import name 'PasswordGenerator' from 'password_generator' 

### ISSUE THREAD

**Issue by tapasfun** [dheeth/Treasure-Cloud-Auto-Referral#1]
File "W:\projects\treasure\Treasure-Cloud-Auto-Referral\main.py", line 5, in <module>
    from password_generator import PasswordGenerator
ImportError: cannot import name 'PasswordGenerator' from 'password_generator' (C:\Users\user\AppData\Roaming\Python\Python39\site-packages\password_generator.py)

**Comment by dheeth** [comment]
I checked and saw that the issue was mainly when we ran the script on remote systems like RDP, therefore added treasure.py for that. Try it and see if it works now, also I have added real typing animation this time

**Comment by dheeth** [comment]
As I got it confirmed from multiple sources that it's working now so I am marking this issue as closed now
